var search = document.querySelector('.search')
var city = document.querySelector('.city')
var search = document.querySelector('.country')
var search = document.querySelector('.search')
var search = document.querySelector('.search')
